name: Example Workflow

run-name: 'Run triggered by ${{github.event_name}}-${{github.sha}} '

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:    

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code code  
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci --verbose


      - name: Install latest Cypress
        run: npm install cypress@latest

      - name: Run tests
        run: npx cypress run   

      - name: Notify Teams on Success
        if: success()
        run: |
         curl -X POST \
         -H "Content-Type: application/json" \
         -d '{
          "text":"✅ Cypress Tests Passed\n\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nRun: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
         }' \
          "${{ secrets.TEAMS_WEBHOOK }}"

      - name: Notify Teams on Failure
        if: failure()
        run: |
         curl -X POST \
         -H "Content-Type: application/json" \
         -d '{
         "type": "AdaptiveCard",
         "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
         "version": "1.4",
         "body": [
          {
            "type": "TextBlock",
            "size": "Large",
            "weight": "Bolder",
            "text": "GitHub Actions Test / ❌ Cypress Tests Failed\n\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nRun: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
         ]
         
         }' \
         "${{ secrets.TEAMS_WEBHOOK }}"